name: 'GESIS Methods Hub Quarto to Jupyter Notebook'
description: 'Convert a Quarto document into a Jupyter Notebook for GESIS Methods Hub'
inputs:
  files:
    description: 'Space separated list of Quarto files to convert into Jupyter Notebook'
    required: false
    default: 'README.qmd'
  version:
    description: 'Version of Quarto'
    required: false
    default: '1.7.29'
  token:
    description: 'GitHub token with write access to the repository'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Quarto 
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: ${{ inputs.version }}
    - name: Fetch Git repository
      uses: actions/checkout@v4
    - shell: bash
      env:
        INPUT_FILES: ${{ inputs.files }}
      run: |
        for file in $INPUT_FILE
        do
          quarto \
          convert \
          $file
        done
    - name: Set up Git user
      shell: bash
      run: |
        git config --global user.name "Methods Hub"
        git config --global user.email "methodshub@gesis.org"
    - name: Commit Jupyter Notebook
      shell: bash
      env:
        INPUT_FILE: ${{ inputs.file }}
      run: |
        git add .
        git commit -m "Record representation of $INPUT_FILE as Jupyter Notebook"
    - name: Push Changes
      shell: bash
      run: |
        git push https://${{ inputs.token }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}