name: Test
on:
  push:
    branches:
      - main
    paths:
      - 'tests/*'
jobs:
  test-github-action:
    runs-on: ubuntu-24.04
    name: Test GitHub Action
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          files: "tests/python.qmd tests/rstats.qmd"
          token: ${{ secrets.GITHUB_TOKEN }}
