name: Test
on:
  push:
    branches:
      - main
jobs:
  test-github-action:
    name: Test GitHub Action
    secrets: inherit
    uses: ${{ github.repository }}/action.yml@${{ github.ref }}
    with:
      file: tests/python.qmd
